### ISSUE TITLE
Error: Cannot find module './../components/registerComponent'

### ISSUE THREAD

**Issue by limcheekin** [multunus/React-Native-TDD-Tutorial#4]
First of all, thanks for sharing the TDD tutorial in details. It will be greatly help for beginner to pick up React Native using the TDD approach.

I clone the git repo locally and execute "npm install" then "npm test" in Windows 7, NodeJs v6.3.1 and Npm v3.10.3, it return the following error:
Error: Cannot find module './../components/registerComponent'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (authContainer.js:2:1)
    at Module._compile (module.js:541:32)
    at loader (C:\dev\ws\react-native\React-Native-TDD-Tutorial\node_modules\babel-register\lib\node
.js:148:5)

Please help. Thank you.

**Comment by Roshanjossey** [comment]
Hey @limcheekin,

I'm quite elated to learn that this tutorial is helping you

I couldn't reproduce the issue you're facing, but I'll give you more context so that you can try to fix this on your own.

import that throws this error is in [this line](https://github.com/multunus/React-Native-TDD-Tutorial/blob/master/src/screens/auth/containers/authContainer.js#L2).

`registerComponent` is exported in [registerComponent.ios.js](https://github.com/multunus/React-Native-TDD-Tutorial/blob/master/src/screens/auth/components/registerComponent.ios.js#L31) and [registerComponent.android.js](https://github.com/multunus/React-Native-TDD-Tutorial/blob/master/src/screens/auth/components/registerComponent.android.js#L6)

Meanwhile I'll also look in to any reasons that might cause it

If this is stopping you, you can also try removing `authContainer`. This will not affect following the tutorial.

Cheers.

**Comment by limcheekin** [comment]
Thanks for quick response.

I tried it on Mac OS, it is working fine. I think the problem only happened on Windows platform.

**Comment by Roshanjossey** [comment]
@limcheekin: Cool.
Happy to learn that you're making progress.

May the source be with you
